### ISSUE TITLE
Super block root watch upstreaming

### ISSUE THREAD

**Issue by dominikh** [amir73il/linux#9]
Are there any plans to upstream your super block root watch work, and if so, is there something resembling a timeline?

**Comment by amir73il** [comment]
The work is queued for next kernel release in fsnotify maintainer's tree.
If all goes well, code should land in kernel pre release 5.1-rc1 mid March
and be available in stable kernel around end of April.

**Comment by dominikh** [comment]
That's amazing. Thank you a lot for your work.
